# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

gallery:
  root: true                # If the main index is the galley right away. This is false by default.
  dir: photos               # Path to the gallery
  symlink: true             # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  auto_orient: false        # False by default. When activated it rotates the images based on the exifr.
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 300                  # max width of thumbnails (in pixels)
    y: 300                  # max height of thumbnails (in pixels)
# The following options are for individual galleries and totally optional.
#  galleries:
#    chile_trip:
#      best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
#    japan_trip:
#      best_image: IMG_0690.JPG
#      name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
#    awesome_stuff:
#      best_image: snaileo_gonzales.jpg
#      sort_reverse: true    # Reverse sort images in gallery.
#    secret_stuff:
#      hidden: true          # Don't show this gallery on the index page. People must guess the URL.
#    with_info:
#      info:
